apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-sample
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/java-sample/java-sample@sha256:2675699a73c08498aafb7bf37f1af876bacb0a1ecdd95a814757bae9053ab289
        name: my-java-quarkus
        resources: {}
status: {}
