apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-sample
    app.kubernetes.io/part-of: java-sample
  name: java-sample
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/java-sample/java-sample@sha256:3909349ef2c871264c13b06366de0e1feec466d09c19276a66ce088751bfc77b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
